spring:
  application:
    name: service-oauth
#  config:
#    import: 'optional:configserver:'
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411/

#Application Configuration
server:
  port: 9100


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

